
services:
#Backend Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: firewall_backend 
    container_name: firewall_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - firewall_network

#PostgreSQL Database Service
  db:
    image: postgres:15
    container_name: firewall_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: firewall_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - firewall_network 
#PgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: firewall_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@firewall.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - firewall_network

#Volumes and Networks
volumes:
  postgres_data:
  pgadmin_data:

networks:
  firewall_network:
  
